### ISSUE TITLE
Russian Language Support

### ISSUE THREAD

**Issue by Ibragimov** [GustavoPeredo/Font-Downloader#4]
Dear Gustavo,

Please, add Russian language to Font Downloader.
It is now 100% translated at POEditor portal.

Have a wonderful day!
Victor Ibragimov

**Comment by Ibragimov** [comment]
[Font_Downloader_Tajik_Russian.zip](https://github.com/GustavoPeredo/font-downloader/files/5303761/Font_Downloader_Tajik_Russian.zip)

**Comment by GustavoPeredo** [comment]
Thank you very much, a beautiful day for you too

**Comment by Ibragimov** [comment]
Please, update Russian translations. Improved!:
[Font_Downloader_Russian.zip](https://github.com/GustavoPeredo/font-downloader/files/5311109/Font_Downloader_Russian.zip)

**Comment by GustavoPeredo** [comment]
Have you updated in poeditor as well?

**Comment by Ibragimov** [comment]
Yes, these files were exported from the POEditor!

**Comment by GustavoPeredo** [comment]
Awesome! I updated them and on the next release they will become available. Thank you!

**Comment by Ibragimov** [comment]
Russian translations for new features is now 100% completed!

[Font_Downloader_Russian.zip](https://github.com/GustavoPeredo/font-downloader/files/5316482/Font_Downloader_Russian.zip)

**Comment by Ibragimov** [comment]
Tested - Russian translations are not yet available. Could you please, re-check!

**Comment by GustavoPeredo** [comment]
WIll check this out as well, thank you

**Comment by GustavoPeredo** [comment]
Russian language support should now be working, but to release the update I'd like to ask you to translate 4 new string in Russian and Tajik (this should fix the non-translated 'Default' button)

**Comment by Ibragimov** [comment]
100% Translated! (on POEditor)

**Comment by GustavoPeredo** [comment]
Awesome! Thank you very much.

I'll push the updates to Flathub today!

**Comment by Ibragimov** [comment]
Russian language is not yet available to test...

**Comment by GustavoPeredo** [comment]
Can you confirm you are running the latest (3.10.1) version?

**Comment by Ibragimov** [comment]
Yes, it is 3.10.1

**Comment by GustavoPeredo** [comment]
![Captura de tela de 2020-10-06 08-28-03](https://user-images.githubusercontent.com/30641461/95196799-f91c0880-07ae-11eb-9921-cd6563cbc3c6.png)

I don't have a russian locale, this is probably why only a portion of the text is translated. I'll be publishing the update as 3.10.2 and hopefully this bug is fixed.

Thank you!

**Comment by GustavoPeredo** [comment]
Update: If you want/have time to test before the official release, you can test the Russian Language already by running this command:
`flatpak install https://dl.flathub.org/build-repo/28406/org.gustavoperedo.FontDownloader.flatpakref`

**Comment by Ibragimov** [comment]
Yes, let me please, test before the official release.
But the below link is not available or misspelled. Could you please, re-check.
https://dl.flathub.org/build-repo/28406/org.gustavoperedo.FontDownloader.flatpakref
bash: https://dl.flathub.org/build-repo/28406/org.gustavoperedo.FontDownloader.flatpakref: No such file or directory

Also it seems the current 3.10.2 still have the issue unresolved.

**Comment by GustavoPeredo** [comment]
> But the below link is not available or misspelled. Could you please, re-check.

The link is only available between the time I push an update and the update being published (around 8 hours), this is why it doesn't exist anymore...

> Also it seems the current 3.10.2 still have the issue unresolved.

Hmmmm, I'll need you tô answer some questions:

Are the translations similar to the one I posted in the screenshot before?

Is nothing translated?

 Is the About Font Downloader Dialog translated?

I'll try to narrow down the issue and hopefully fix it.

**Comment by Ibragimov** [comment]
It is in English. Only desktop shortcut looks translated.

![Russian-2020-10-07-15-50-08](https://user-images.githubusercontent.com/1321588/95321930-2d79ec80-08b5-11eb-8188-49bede6b4a1f.png)
![Russian-2020-10-07-15-50-22](https://user-images.githubusercontent.com/1321588/95321937-2fdc4680-08b5-11eb-99ea-610487c8bebf.png)

**Comment by GustavoPeredo** [comment]
Thank you very much, I'll be looking into it

**Comment by GustavoPeredo** [comment]
I'm back at fixing this issue! Finally! So, I reran xgettext and it detected many new texts, so, I'll update this issue soon.

**Comment by GustavoPeredo** [comment]
I'll close due to inactivity, but if the issue is still present, I'll start working on it again.

**Comment by Ibragimov** [comment]
Dear Gustavo,

I will provide more details once I get back to testing the Russian language support.
That is OK to close this issue by now, so we can open it a bit later or upon request.

Thank you for such a great app!

Have a wonderful day!
Victor Ibragimov

**Comment by GustavoPeredo** [comment]
Thank you very much for your support :)

**Comment by Ibragimov** [comment]
Dear Gustavo,

I have just tested Russian translation for Font Downloader and it looks like the app is still shown in Tajik ;-)
On the app menu list the app name appear in Russian, but the entire app is in Tajik... Could you please, check it again?

Thank you for prompt reply,
Victor Ibragimov

![KDE Neon-2021-04-18-20-20-06](https://user-images.githubusercontent.com/1321588/115150895-cf0fa100-a083-11eb-82e6-5c2756652306.png)
![KDE Neon-2021-04-18-20-20-16](https://user-images.githubusercontent.com/1321588/115150899-d20a9180-a083-11eb-961c-74efe9d553b1.png)

**Comment by GustavoPeredo** [comment]
Dear @Ibragimov ,

Thanks for telling me about the issue, I'll start investigating the issue soon.
Can you tell me which linux distribution you are using? 

Gustavo :)

**Comment by Ibragimov** [comment]
Dear Gustavo,

It was tested on the latest version on KDE Neon.

Kind regards,
Victor Ibragimov
